// Mechanical backstop for issue #628 (a fabricated `Claude-Session:` footer on
// a GitHub comment recurred two days after #605/#606's prose-only fix, because
// `session-id-guard.ts` only ever sees git commit trailers) — broadened by the
// ADR-0017 2026-07-31 amendment to also close issue #737.
//
// What it enforces is now the ADR's actual requirement rather than one spelling
// of it: **an agent-authored GitHub body carries a full session URL naming THIS
// session.** Format-agnostic on purpose — the provenance header, the legacy
// two-line footer, and the harness's own `_Generated by [Claude Code](<url>)_`
// all satisfy it (`sessionIdsIn`). That is what lets the repo convention stop
// competing with the harness's footer: either shape is provenance, so an agent
// that follows the harness is not thereby in breach.
//
// Two findings, where there was previously one:
//   • `missing`  — the body carries no session URL at all. This is #737: the
//     old check fired only on a DIVERGENT footer, so a body with no provenance
//     whatsoever passed. Both observed misses (PRs #755, #782) were this case.
//   • `mismatch` — the body names a session, but not this one. The original
//     #628 regression.
//
// A `PreToolUse` hook (wired in `.claude/settings.json`, same template as
// `deferred-tool-guard.ts`, #612) matches every GitHub-writing tool whose body
// can carry provenance (`GITHUB_PROVENANCE_TOOLS`). It resolves ground truth
// from the hook payload's `transcript_path` the same way `session-id-guard.ts`
// does for commits (`resolveGroundTruthFromTranscript`, reused not re-derived).
//
// Skip-and-pass (never a false failure) when no ground truth is resolvable, or
// when the call carries no body field at all — the latter matters: a
// label-or-state-only `issue_write` update has no body to stamp, and denying
// those would wedge the triage sweep. Only a body that EXISTS is policed.
//
// Runs before the post, closing the gap #605/#606 could only document; it can't
// fix an already-posted body (no edit-comment tool exists — the standing remedy
// is still a follow-up correction comment) or a non-tool-mediated post.
//
// Pure core (`checkGithubProvenance`) is kept separate from the stdin/transcript
// I/O (`main`), mirroring `deferred-tool-guard.ts` / `session-id-guard.ts`.
//
// Usage (normally invoked by the PreToolUse hook with the payload on stdin):
//   tsx scripts/github-provenance-guard.ts
import { readFileSync } from 'node:fs'
import { pathToFileURL } from 'node:url'
import { SESSION_TRAILER } from './git-helpers.ts'
import { provenanceHeader, readProvenanceHeader, sessionIdsIn } from './provenance-header.ts'
import { resolveGroundTruthFromTranscript } from './session-id-guard.ts'

/** A global copy of `SESSION_TRAILER` for `matchAll` (issue #692) — the legacy
 *  footer's last-match rule needs every occurrence. Built locally rather than
 *  adding the `g` flag to the shared export: `provenance-footer.ts` calls
 *  `SESSION_TRAILER.test()`, which is stateful (`lastIndex`) on a global regex
 *  and would break under repeated calls. */
const SESSION_TRAILER_GLOBAL = new RegExp(SESSION_TRAILER.source, 'g')

/** One GitHub-writing tool whose call can carry agent-authored provenance, and
 *  which of its parameters holds that text. Verified against each tool's real
 *  schema via `ToolSearch` (issue #628 — CLAUDE.md: never guess a deferred
 *  tool's shape) — every one of these uses `body`, but the field is still
 *  named per entry so a future addition with a different field name is a
 *  one-line row, not a logic change. */
export interface ProvenanceTool {
  tool: string
  bodyField?: string
}

/** The registry: every GitHub MCP tool that writes a comment, issue, PR, or
 *  review body an agent must stamp with provenance (ADR-0017). Add a row here
 *  if a new provenance-carrying surface is found.
 *
 *  MCP-API commits (`create_or_update_file` / `push_files`) are deliberately
 *  ABSENT: their `message` is a commit message, which belongs to the footer
 *  surface, not this one — see `docs/agents/provenance.md`'s coverage map for
 *  that still-open hole. */
export const GITHUB_PROVENANCE_TOOLS: readonly ProvenanceTool[] = [
  { tool: 'mcp__github__add_issue_comment' },
  { tool: 'mcp__github__add_reply_to_pull_request_comment' },
  { tool: 'mcp__github__create_pull_request' },
  { tool: 'mcp__github__update_pull_request' },
  { tool: 'mcp__github__pull_request_review_write' },
  { tool: 'mcp__github__add_comment_to_pending_review' },
  { tool: 'mcp__github__issue_write' },
]

/** `missing` — no session URL at all (issue #737); `mismatch` — a session URL
 *  naming someone else (issue #628). `found` is absent on a `missing`. */
export interface ProvenanceFinding {
  kind: 'missing' | 'mismatch'
  tool: string
  found?: string
  expected: string
}

/** The pure, unit-testable core: does this call's body carry a full session URL
 *  naming the resolved ground truth, in ANY recognized shape?
 *
 *  Returns `null` for anything compliant or out of scope — a tool outside the
 *  registry, a call with no body field at all (a label-only `issue_write`; see
 *  the header for why those must pass), a body already naming this session, or
 *  (skip-and-pass, never a false failure) no resolvable ground truth. Never
 *  throws. */
export function checkGithubProvenance(
  toolName: string,
  toolInput: unknown,
  groundTruthId: string | null | undefined,
  registry: readonly ProvenanceTool[] = GITHUB_PROVENANCE_TOOLS,
): ProvenanceFinding | null {
  if (!groundTruthId) return null
  const entry = registry.find((r) => r.tool === toolName)
  if (!entry) return null
  if (toolInput === null || typeof toolInput !== 'object') return null
  const body = (toolInput as Record<string, unknown>)[entry.bodyField ?? 'body']
  // A call with no body carries nothing to stamp — not a violation (header).
  if (typeof body !== 'string' || body.trim() === '') return null

  // Adjudicated most-canonical slot first, so a body that HAS a designated
  // provenance slot is judged on that slot alone — a body may legitimately
  // quote another session's URL as evidence (issue #692), and a quote must
  // neither satisfy nor break the check.
  const header = readProvenanceHeader(body)
  if (header) {
    const found = sessionIdsIn(header.sessionUrl)[0]
    return found === groundTruthId ? null : { kind: 'mismatch', tool: toolName, found, expected: groundTruthId }
  }

  // No header: fall back to the legacy footer's own rule, unchanged — the LAST
  // `Claude-Session:` trailer is the body's own, earlier ones are citations
  // (issue #692). Preserved verbatim so pre-amendment content and any agent
  // still writing the footer keep exactly the guarantee they had.
  const trailer = [...body.matchAll(SESSION_TRAILER_GLOBAL)].at(-1)
  if (trailer) {
    const found = trailer[1]!
    return found === groundTruthId ? null : { kind: 'mismatch', tool: toolName, found, expected: groundTruthId }
  }

  // Neither: the harness's own `_Generated by [Claude Code](<url>)_` still
  // satisfies ADR-0017's actual requirement, so accept any session URL naming
  // us. No last-match adjudication here — with no designated slot there is no
  // basis to call one occurrence "the" provenance.
  const ids = sessionIdsIn(body)
  if (ids.length === 0) return { kind: 'missing', tool: toolName, expected: groundTruthId }
  if (ids.includes(groundTruthId)) return null
  return { kind: 'mismatch', tool: toolName, found: ids.at(-1)!, expected: groundTruthId }
}

/** The corrective message shown to the agent when the guard blocks — names the
 *  offending tool and the real session id, and restates the rule so it is
 *  self-contained without the agent having read CLAUDE.md or provenance.md.
 *  The `missing` branch shows the exact header to paste, because an agent that
 *  forgot provenance entirely needs the format, not just the id. */
export function formatGuardMessage(f: ProvenanceFinding): string {
  const url = `https://claude.ai/code/${f.expected}`
  if (f.kind === 'missing') {
    return (
      `Blocked (ADR-0017 provenance guard, issue #737): the \`${f.tool}\` call's body carries no ` +
      `session URL, so its authorship would not be recoverable from the content. Add the ` +
      `provenance header as the body's FIRST line:\n\n` +
      `${provenanceHeader('<your model name>', url)}\n\n` +
      `Use ${url} verbatim — this hook already resolved it from the transcript; never ` +
      `reconstruct a session id from memory. Leave any footer the harness appends alone.`
    )
  }
  return (
    `Blocked (ADR-0017 provenance guard, issue #628): the \`${f.tool}\` call's body names session ` +
    `${f.found}, but this session's resolved ground-truth id is ${f.expected}. Never predict or ` +
    `reconstruct a session id from memory — this hook already resolved the real one from the ` +
    `transcript; use ${url} verbatim.`
  )
}

/** The `PreToolUse` "deny" control object a hook writes to stdout to block a
 *  call (Claude Code hooks reference). `null` when nothing should be blocked,
 *  so `main` writes nothing and the call proceeds untouched. */
export function denyOutputFor(finding: ProvenanceFinding | null): { hookSpecificOutput: Record<string, string> } | null {
  if (!finding) return null
  return {
    hookSpecificOutput: {
      hookEventName: 'PreToolUse',
      permissionDecision: 'deny',
      permissionDecisionReason: formatGuardMessage(finding),
    },
  }
}

/** Hook payload shape we rely on — a subset of the PreToolUse stdin JSON.
 *  `transcript_path` is what `session-end.ts` already reads off the same
 *  payload shape (confirmed there, not guessed here). */
interface PreToolUsePayload {
  tool_name?: string
  tool_input?: unknown
  transcript_path?: string
}

/** Reads the hook JSON on stdin, resolves ground truth from the transcript,
 *  runs the pure check, and — only on a mismatch — writes the deny control
 *  object to stdout. Always exits 0: an allowed call, a missing transcript
 *  (no ground truth resolvable), or any parse/read failure must let normal
 *  tool use proceed. This is a backstop, so it fails OPEN. */
export function main(): void {
  let raw: string
  try {
    raw = readFileSync(0, 'utf8')
  } catch {
    return // no stdin — nothing to inspect
  }
  if (!raw.trim()) return

  let payload: PreToolUsePayload
  try {
    payload = JSON.parse(raw)
  } catch {
    return // not JSON — do not interfere
  }
  if (typeof payload.tool_name !== 'string') return
  if (!payload.transcript_path) return // no transcript path — no ground truth resolvable, skip-and-pass

  let transcriptJsonl: string
  try {
    transcriptJsonl = readFileSync(payload.transcript_path, 'utf8')
  } catch {
    return // transcript unreadable — skip-and-pass, same contract
  }

  const groundTruthId = resolveGroundTruthFromTranscript(transcriptJsonl)
  const finding = checkGithubProvenance(payload.tool_name, payload.tool_input, groundTruthId)
  const output = denyOutputFor(finding)
  if (output) process.stdout.write(JSON.stringify(output))
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? '').href) {
  try {
    main()
  } catch {
    // A hook must never wedge tool use with its own crash — swallow and allow.
  }
}
