// The ADR-0017 provenance HEADER — the format agents stamp on GitHub bodies
// (issues, PR descriptions, comments, reviews) as of the 2026-07-31 amendment.
//
// Why a header and not the two-line footer this repo used before: the harness
// appends its own attribution footer to PR bodies and comments, and ADR-0017's
// footer had to compete with it for the same trailing position. Measured over
// every agent-authored artefact in the window after `docs/agents/provenance.md`
// landed, 22 of 23 PR bodies carried BOTH footers, and the two that carried only
// one had lost ADR-0017's — the harness's won. A header occupies a position
// nothing else claims, so the two stop fighting and neither is dropped.
//
// The load-bearing property is NOT the format: it is that a **full session URL**
// is present, so authorship stays recoverable from the content itself (ADR-0017's
// Context). That is why `sessionIdsIn` reads every shape — this header, the old
// two-line footer, and the harness's own `_Generated by [Claude Code](<url>)_` —
// rather than pinning one. Old content stays readable and the harness's footer
// counts as provenance on its own.
//
// Commits are deliberately NOT covered here: a commit message renders no markdown,
// and the harness's commit template already emits the two-line trailer that
// `provenance-footer.ts` backstops. That surface has no conflict to resolve.
import { SESSION_TRAILER } from './git-helpers.ts'

/** The bot icon opening the header. Single-homed so the builder and the
 *  detector can't drift. */
export const BOT_ICON = '🤖'

/** The ADR-0017 provenance header: bot icon, model name, linked to the session.
 *  The single code home for the format — `reconstructFooterValues()`
 *  (provenance-footer.ts) resolves both arguments for the current session, so a
 *  caller never hand-assembles either value (CLAUDE.md: never reconstruct an
 *  identifier from memory). */
export function provenanceHeader(modelName: string, sessionUrl: string): string {
  return `${BOT_ICON} [${modelName}](${sessionUrl})`
}

/** Prepend `header` as the body's own first paragraph, leaving the rest — and
 *  anything the harness later appends at the bottom — untouched. */
export function applyHeader(body: string, header: string): string {
  return `${header}\n\n${body.replace(/^\s+/, '')}`
}

/** A full session URL, wherever it appears and whatever wraps it: the header's
 *  markdown link, a `Claude-Session:` trailer, or the harness's own
 *  `_Generated by [Claude Code](<url>)_`. Global — a body may legitimately
 *  quote another session's URL as evidence, so callers decide which match
 *  matters rather than assuming there is one. */
const SESSION_URL_GLOBAL = /https:\/\/claude\.ai\/code\/(session_[A-Za-z0-9_-]+)/g

/** The header specifically — captures the model name and the session URL. Used
 *  to read a header back (and by tests); presence checks should prefer
 *  `sessionIdsIn`, which is format-agnostic by design. */
export const PROVENANCE_HEADER = /^\s*🤖\s*\[([^\]]+)\]\((https:\/\/claude\.ai\/code\/session_[A-Za-z0-9_-]+)\)\s*$/m

/** Every session id `text` references, in order, deduped. The provenance
 *  primitive: "is a full session URL present, and which session does it name?"
 *  — the question ADR-0017 actually cares about, asked without pinning a
 *  format. Reads the header, the legacy `Claude-Session:` trailer, and the
 *  harness footer alike. */
export function sessionIdsIn(text: string): string[] {
  const ids = [...text.matchAll(SESSION_URL_GLOBAL)].map((m) => m[1]!)
  // The legacy footer's trailer may carry a bare id rather than a full URL.
  const trailer = SESSION_TRAILER.exec(text)
  if (trailer?.[1]) ids.push(trailer[1])
  return [...new Set(ids)]
}

/** True when `text` carries provenance in ANY recognized shape. The authorship
 *  signal `check-triage-drift.ts`'s `isAiAuthored` is built on. */
export function hasProvenance(text: string): boolean {
  return sessionIdsIn(text).length > 0
}

/** The model name and session URL a header names, or `null` when `text` has no
 *  header. Lets a reader recover both without re-deriving the regex. */
export function readProvenanceHeader(text: string): { modelName: string; sessionUrl: string } | null {
  const m = PROVENANCE_HEADER.exec(text)
  return m ? { modelName: m[1]!.trim(), sessionUrl: m[2]! } : null
}
