// Unit tests for the triage-drift detector's pure core (issue #507):
// AI-authorship detection (the ADR-0017 footer signal), the claimed-label
// phrase matcher, the most-recent-AI-comment pick, and the per-issue drift
// check. The `gh api` / REST shell is a thin wrapper over these, exercised by
// running the script directly. The shared `gh`/`rest` strategy decision
// (`pickFetchStrategy`, `parseNextLink`) is single-homed in `list-open-issues.ts`
// (issue #505) and tested there.
import { describe, expect, it } from 'vitest'
import {
  CANONICAL_LABELS,
  findClaimedLabelTransitions,
  findTriageDrift,
  isAiAuthored,
  latestClaimedLabel,
  mostRecentAiComment,
  toDriftCheckIssue,
  type RawCommentApiRecord,
} from '../../scripts/check-triage-drift.ts'
import type { RawIssueApiRecord } from '../../scripts/list-open-issues.ts'

// A real AI-authored comment body, lifted from issue #325's second comment —
// the exact motivating example from #507.
const ISSUE_325_UPDATE_COMMENT = `> *This was generated by AI during triage.*

**Update: moved to \`ready-for-agent\`.** The maintainer (Trusted) has green-lit agent implementation.

Co-Authored-By: Claude Opus 4.8 <noreply@anthropic.com>
Claude-Session: https://claude.ai/code/session_01VhL2mH3yYgkDqrMv61qe11

---
_Generated by [Claude Code](https://claude.ai/code)_`

const ISSUE_325_BRIEF_COMMENT = `> *This was generated by AI during triage.*

## Brief (ready-for-human)

**Category:** enhancement

Co-Authored-By: Claude Opus 4.8 <noreply@anthropic.com>
Claude-Session: https://claude.ai/code/session_01VhL2mH3yYgkDqrMv61qe11`

describe('isAiAuthored()', () => {
  it('is true for a comment carrying the ADR-0017 provenance footer', () => {
    expect(isAiAuthored(ISSUE_325_UPDATE_COMMENT)).toBe(true)
  })
  it('is case-insensitive on the footer', () => {
    expect(isAiAuthored('co-Authored-BY: Someone <noreply@anthropic.com>')).toBe(true)
  })
  it('is false for an ordinary human comment', () => {
    expect(isAiAuthored('makes sense, an agent should give this a try')).toBe(false)
  })
  it('is false for a footer-shaped line with a different domain', () => {
    expect(isAiAuthored('Co-Authored-By: Someone <someone@example.com>')).toBe(false)
  })
})

describe('findClaimedLabelTransitions()', () => {
  it('finds "moved to `label`" claims', () => {
    expect(findClaimedLabelTransitions(ISSUE_325_UPDATE_COMMENT)).toEqual([
      { label: 'ready-for-agent', index: expect.any(Number) },
    ])
  })
  it('does not match a label mentioned without a transition verb', () => {
    expect(findClaimedLabelTransitions(ISSUE_325_BRIEF_COMMENT)).toEqual([])
  })
  it('matches "labeled X" and "marked X" phrasings', () => {
    expect(latestClaimedLabel('This issue is now labeled needs-info, please clarify.')).toBe('needs-info')
    expect(latestClaimedLabel('Closing as not planned — marked wontfix.')).toBe('wontfix')
  })
  it('matches "stamp `X`" (the auto-triage SKILL.md phrasing)', () => {
    expect(latestClaimedLabel('Stamp `ready-for-agent` and post a brief.')).toBe('ready-for-agent')
  })
  it('matches every canonical label, not just a hardcoded subset', () => {
    for (const label of CANONICAL_LABELS) {
      expect(latestClaimedLabel(`moved to \`${label}\` after review.`)).toBe(label)
    }
  })
  it('is case-insensitive and tolerates missing backticks', () => {
    expect(latestClaimedLabel('MOVED TO READY-FOR-AGENT.')).toBe('ready-for-agent')
  })
  it('returns null when the comment makes no recognizable claim', () => {
    expect(latestClaimedLabel('Thanks for the report, taking a look.')).toBeNull()
  })
})

describe('latestClaimedLabel()', () => {
  it('picks the rightmost (last) claim when a comment narrates a transition', () => {
    expect(
      latestClaimedLabel('Previously labeled needs-info; now moved to `ready-for-agent`.'),
    ).toBe('ready-for-agent')
  })
})

describe('mostRecentAiComment()', () => {
  const human: RawCommentApiRecord = {
    html_url: 'https://github.com/x/y/issues/1#issuecomment-1',
    body: 'looks good to me',
    created_at: '2026-07-10T00:00:00Z',
  }
  const aiOld: RawCommentApiRecord = {
    html_url: 'https://github.com/x/y/issues/1#issuecomment-2',
    body: ISSUE_325_BRIEF_COMMENT,
    created_at: '2026-07-11T23:34:03Z',
  }
  const aiNew: RawCommentApiRecord = {
    html_url: 'https://github.com/x/y/issues/1#issuecomment-3',
    body: ISSUE_325_UPDATE_COMMENT,
    created_at: '2026-07-11T23:41:13Z',
  }

  it('picks the newest AI-authored comment, ignoring human comments and older AI ones', () => {
    expect(mostRecentAiComment([human, aiOld, aiNew])).toEqual(aiNew)
  })
  it('returns null when no comment is AI-authored', () => {
    expect(mostRecentAiComment([human])).toBeNull()
  })
  it('returns null for an empty comment list', () => {
    expect(mostRecentAiComment([])).toBeNull()
  })
})

describe('findTriageDrift()', () => {
  const aiComment: RawCommentApiRecord = {
    html_url: 'https://github.com/feffef/terrarium/issues/325#issuecomment-4949195322',
    body: ISSUE_325_UPDATE_COMMENT,
    created_at: '2026-07-11T23:41:13Z',
  }

  it('flags issue #325\'s real drift: claimed ready-for-agent, live label ready-for-human', () => {
    expect(
      findTriageDrift(
        { number: 325, title: 'Dev-server manifest watch', labels: ['enhancement', 'ready-for-human'] },
        [aiComment],
      ),
    ).toEqual({
      number: 325,
      title: 'Dev-server manifest watch',
      claimedLabel: 'ready-for-agent',
      liveLabels: ['enhancement', 'ready-for-human'],
      commentUrl: aiComment.html_url,
      commentCreatedAt: aiComment.created_at,
    })
  })

  it('does not flag when the live labels already match the claim', () => {
    expect(
      findTriageDrift({ number: 1, title: 'x', labels: ['ready-for-agent'] }, [aiComment]),
    ).toBeNull()
  })

  it('does not flag when there is no AI-authored comment', () => {
    const human: RawCommentApiRecord = {
      html_url: 'https://github.com/x/y/issues/1#issuecomment-9',
      body: 'moved to ready-for-agent, I think',
      created_at: '2026-07-11T23:41:13Z',
    }
    expect(findTriageDrift({ number: 1, title: 'x', labels: ['needs-triage'] }, [human])).toBeNull()
  })

  it('does not flag when the AI comment makes no recognizable claim', () => {
    const noClaim: RawCommentApiRecord = {
      html_url: 'https://github.com/x/y/issues/1#issuecomment-9',
      body: 'Co-Authored-By: Claude <noreply@anthropic.com>\nJust looked into this, no update yet.',
      created_at: '2026-07-11T23:41:13Z',
    }
    expect(findTriageDrift({ number: 1, title: 'x', labels: ['needs-triage'] }, [noClaim])).toBeNull()
  })
})

describe('toDriftCheckIssue()', () => {
  it('maps a plain issue record, decoding the title and flattening labels', () => {
    const record: RawIssueApiRecord = {
      number: 325,
      title: 'Dev server &amp; manifest watch',
      labels: [{ name: 'enhancement' }, 'ready-for-human'],
      updated_at: '2026-07-11T23:41:13Z',
    }
    expect(toDriftCheckIssue(record)).toEqual({
      number: 325,
      title: 'Dev server & manifest watch',
      labels: ['enhancement', 'ready-for-human'],
    })
  })
  it('returns null for a record that is actually a pull request', () => {
    const record: RawIssueApiRecord = {
      number: 507,
      title: 'a pr',
      labels: [],
      updated_at: '2026-07-16T00:00:00Z',
      pull_request: { url: 'https://api.github.com/repos/feffef/terrarium/pulls/507' },
    }
    expect(toDriftCheckIssue(record)).toBeNull()
  })
})
