// Coverage for the ADR-0017 provenance HEADER (2026-07-31 amendment) — see the
// ADR for why the convention moved off a trailing footer.
//
// Two assertions here are load-bearing and easy to break by "simplifying":
//   • the header is anchored to the START of a body, so a QUOTED header (or this
//     repo's own doc example, which embeds a real id) is never read as the body's
//     own provenance — issue #692's class of bug, reachable through the new marker.
//   • `hasAuthorshipMarker` requires a deliberate marker, NOT merely a session URL:
//     a human pasting one in prose must not read as agent-authored, or
//     `guest-intake-scan.ts` silently stops answering them.
import { describe, expect, it } from 'vitest'
import {
  BOT_ICON,
  hasAuthorshipMarker,
  provenanceHeader,
  readProvenanceHeader,
  sessionIdsIn,
} from '../../scripts/provenance-header.ts'

const URL = 'https://claude.ai/code/session_019hdkXjoebyR8etKVNyjn7S'
const ID = 'session_019hdkXjoebyR8etKVNyjn7S'

describe('provenanceHeader() — the format', () => {
  it('is a bot icon, the model name, and a markdown link to the session', () => {
    expect(provenanceHeader('Claude Opus 5', URL)).toBe(`${BOT_ICON} [Claude Opus 5](${URL})`)
  })

  it('round-trips through readProvenanceHeader(), yielding the id callers compare', () => {
    expect(readProvenanceHeader(provenanceHeader('Claude Opus 5', URL))).toEqual({
      modelName: 'Claude Opus 5',
      sessionId: ID,
    })
  })

  it('is read off the head of a real body', () => {
    expect(readProvenanceHeader(`${provenanceHeader('Claude Opus 5', URL)}\n\nFixed the thing.`)?.sessionId).toBe(ID)
  })

  it('THE ANCHOR: a header QUOTED mid-body is NOT read as the body\'s own (the #692 class)', () => {
    const quoting = `Evidence from a prior post:\n\n${provenanceHeader('Claude Opus 5', URL)}\n\nmy prose`
    expect(readProvenanceHeader(quoting)).toBeNull()
  })

  it('is not fooled by the repo\'s own doc example embedded in a body', () => {
    const body = 'See provenance.md:\n\n```\n' + provenanceHeader('Claude Opus 5', URL) + '\n```\n'
    expect(readProvenanceHeader(body)).toBeNull()
  })

  it('returns null for a body with no header', () => {
    expect(readProvenanceHeader('just prose')).toBeNull()
  })
})

describe('sessionIdsIn() — format-agnostic by design', () => {
  it('reads the header', () => {
    expect(sessionIdsIn(provenanceHeader('Claude Opus 5', URL))).toEqual([ID])
  })

  it('reads the LEGACY two-line footer, so pre-amendment content stays attributable', () => {
    expect(sessionIdsIn(`done\n\nCo-Authored-By: Claude Opus 5 <noreply@anthropic.com>\nClaude-Session: ${URL}`)).toEqual([ID])
  })

  it("reads the HARNESS's own footer — the repo convention must not fight it", () => {
    expect(sessionIdsIn(`a PR body\n\n---\n_Generated by [Claude Code](${URL})_`)).toEqual([ID])
  })

  it('returns every distinct id when a body quotes another session as evidence (issue #692)', () => {
    const body = `${provenanceHeader('Claude Opus 5', URL)}\n\nprior regression: https://claude.ai/code/session_OLD`
    expect(sessionIdsIn(body)).toEqual([ID, 'session_OLD'])
  })

  it('does NOT read a bare id with no URL — the legacy trailer alone is not a session URL', () => {
    expect(sessionIdsIn('Claude-Session: session_ABC')).toEqual([])
  })

  it('finds nothing in a body with no provenance, and in the harness footer with no session id', () => {
    expect(sessionIdsIn('just a plain comment')).toEqual([])
    expect(sessionIdsIn('---\n_Generated by [Claude Code](https://claude.ai/code)_')).toEqual([])
  })
})

describe('hasAuthorshipMarker() — the authorship signal isAiAuthored() is built on', () => {
  it('is true for each deliberate marker', () => {
    expect(hasAuthorshipMarker(provenanceHeader('Claude Opus 5', URL))).toBe(true)
    expect(hasAuthorshipMarker(`x\n\nCo-Authored-By: Claude Opus 5 <noreply@anthropic.com>\nClaude-Session: ${URL}`)).toBe(true)
    expect(hasAuthorshipMarker(`x\n\n_Generated by [Claude Code](${URL})_`)).toBe(true)
  })

  it('THE FALSE-POSITIVE GUARD: a human pasting a session URL in prose is NOT agent-authored', () => {
    expect(hasAuthorshipMarker('I saw this in https://claude.ai/code/session_X — please fix')).toBe(false)
    expect(hasAuthorshipMarker('a human wrote this')).toBe(false)
  })
})
