// Coverage for the ADR-0017 provenance HEADER (2026-07-31 amendment). The
// header replaced the two-line footer on GitHub bodies because the harness
// appends its own footer to the same trailing position and ADR-0017's was the
// one being dropped (PRs #755, #782).
//
// The load-bearing assertions here are the format-agnostic ones: `sessionIdsIn`
// must read the header, the legacy footer, AND the harness's own footer, since
// the requirement is "a full session URL is present", not "this exact spelling".
import { describe, expect, it } from 'vitest'
import {
  applyHeader,
  BOT_ICON,
  hasProvenance,
  provenanceHeader,
  readProvenanceHeader,
  sessionIdsIn,
} from '../../scripts/provenance-header.ts'

const URL = 'https://claude.ai/code/session_019hdkXjoebyR8etKVNyjn7S'
const ID = 'session_019hdkXjoebyR8etKVNyjn7S'

describe('provenanceHeader() — the format', () => {
  it('is a bot icon, the model name, and a markdown link to the session', () => {
    expect(provenanceHeader('Claude Opus 5', URL)).toBe(`${BOT_ICON} [Claude Opus 5](${URL})`)
  })

  it('round-trips through readProvenanceHeader()', () => {
    expect(readProvenanceHeader(provenanceHeader('Claude Opus 5', URL))).toEqual({
      modelName: 'Claude Opus 5',
      sessionUrl: URL,
    })
  })

  it('is detected as the FIRST line of a real body, not just standalone', () => {
    const body = applyHeader('Fixed the thing.\n\nDetails follow.', provenanceHeader('Claude Opus 5', URL))
    expect(body.startsWith(`${BOT_ICON} [Claude Opus 5](${URL})`)).toBe(true)
    expect(readProvenanceHeader(body)?.sessionUrl).toBe(URL)
  })

  it('applyHeader() leaves whatever the harness appends at the bottom untouched', () => {
    const withHarnessFooter = 'Body text.\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_'
    const out = applyHeader(withHarnessFooter, provenanceHeader('Claude Opus 5', URL))
    expect(out).toContain('_Generated by [Claude Code](https://claude.ai/code)_')
    expect(readProvenanceHeader(out)?.sessionUrl).toBe(URL)
  })

  it('returns null for a body with no header', () => {
    expect(readProvenanceHeader('just prose')).toBeNull()
  })
})

describe('sessionIdsIn() — format-agnostic by design', () => {
  it('reads the header', () => {
    expect(sessionIdsIn(provenanceHeader('Claude Opus 5', URL))).toEqual([ID])
  })

  it('reads the LEGACY two-line footer, so pre-amendment content stays attributable', () => {
    expect(sessionIdsIn(`done\n\nCo-Authored-By: Claude Opus 5 <noreply@anthropic.com>\nClaude-Session: ${URL}`)).toEqual([ID])
  })

  it("reads the HARNESS's own footer — the repo convention must not fight it", () => {
    expect(sessionIdsIn(`a PR body\n\n---\n_Generated by [Claude Code](${URL})_`)).toEqual([ID])
  })

  it('returns every distinct id when a body quotes another session as evidence (issue #692)', () => {
    const body = `${provenanceHeader('Claude Opus 5', URL)}\n\nprior regression: https://claude.ai/code/session_OLD`
    expect(sessionIdsIn(body)).toEqual([ID, 'session_OLD'])
  })

  it('finds nothing in a body with no provenance, and in the harness footer with no session id', () => {
    expect(sessionIdsIn('just a plain comment')).toEqual([])
    expect(sessionIdsIn('---\n_Generated by [Claude Code](https://claude.ai/code)_')).toEqual([])
  })
})

describe('hasProvenance() — the authorship signal isAiAuthored() is built on', () => {
  it('is true for every recognized shape and false for plain prose', () => {
    expect(hasProvenance(provenanceHeader('Claude Opus 5', URL))).toBe(true)
    expect(hasProvenance(`x\n\nClaude-Session: ${URL}`)).toBe(true)
    expect(hasProvenance(`x\n\n_Generated by [Claude Code](${URL})_`)).toBe(true)
    expect(hasProvenance('a human wrote this')).toBe(false)
  })
})
